version: '3.7'

services:
  backend_api:
    container_name : backen_api
    image: devops-backend_api 
    networks:
      - app-network
    depends_on:
      - Database

  Database:
    container_name: my-postgres
    image: mypostgres:latest
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    networks:
      - app-network

  http_server:
    container_name: server
    image: devops-http_server
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend_api

networks:
  app-network:

